### ISSUE TITLE
"/etc/portage/make.conf", line 27: No closing quotation

### ISSUE THREAD

**Issue by Chevek** [orchid-linux/orchid#1]
In KDE version (possibly more), there is a quote at the end of the make.conf which should not be there.

~ $ emerge --sync
"/etc/portage/make.conf", line 27: No closing quotation
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/emerge", line 51, in <module>
    retval = emerge_main()
  File "/usr/lib/python3.10/site-packages/_emerge/main.py", line 1287, in emerge_main
    emerge_config = load_emerge_config(action=myaction, args=myfiles, opts=myopts)
  File "/usr/lib/python3.10/site-packages/portage/proxy/objectproxy.py", line 31, in __call__
    return result(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/_emerge/actions.py", line 2876, in load_emerge_config
    emerge_config.trees = portage.create_trees(trees=emerge_config.trees, **kwargs)
  File "/usr/lib/python3.10/site-packages/portage/__init__.py", line 655, in create_trees
    settings = config(
  File "/usr/lib/python3.10/site-packages/portage/package/ebuild/config.py", line 447, in __init__
    mygcfg = getconfig(
  File "/usr/lib/python3.10/site-packages/portage/util/__init__.py", line 781, in getconfig
    getconfig(
  File "/usr/lib/python3.10/site-packages/portage/util/__init__.py", line 857, in getconfig
    key = _unicode_decode(lex.get_token())
  File "/usr/lib/python3.10/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.10/shlex.py", line 191, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

**Comment by Chevek** [comment]
This is the culprit:
`echo "$(cpuid2cpuflags | sed 's/: /="/')\"" >> /etc/portage/make.conf`
in install/chroot-ops/install-chroot/postinstall-in-chroot.sh

If cpuid2cpuflags is not there, result is "

**Comment by Chevek** [comment]
Proposed fix to test:
https://github.com/orchid-linux/orchid/tree/cpuid

**Comment by Chevek** [comment]
Fix pushed into main.
https://github.com/orchid-linux/orchid/commit/4e29bd7d5d9abe2234e199ed80e7b460e9ce3840
